		<p align= center><font face="Tahoma" size=2 color=#3f8cff><b>АРХИВ НОВОСТЕЙ</b></font></p>

		<p align=center>
		<table border=0 width=100%>


		<tr><td>
		<font size=2 face="Tahoma" style="color: black"><b>29 ДЕКАБРЯ 2007</font></b><br>
		<font size=2 face="Tahoma">
		<img src="Images1/1.gif">&nbsp; 
		Viru Keemia Grupp планирует делать цемент из отходов<br>
		<a href="uudised_vene\2007\uudis29_12.htm" target="_top"><font size=2 face="Tahoma" color=red>Подробнее...</font></a><br><br>
		</td></tr>

		<tr><td>
		<font size=2 face="Tahoma" style="color: black"><b>28 ДЕКАБРЯ 2007</font></b><br>
		<font size=2 face="Tahoma">
		<img src="Images1/1.gif">&nbsp; 
		Подорожание будет повсеместным<br>
		<a href="uudised_vene\2007\uudis28a_12.htm" target="_top"><font size=2 face="Tahoma" color=red>Подробнее...</font></a><br><br>
		<font size=2 face="Tahoma">
		<img src="Images1/1.gif">&nbsp; 
		Как остаться победителем после открытия рынка<br>
		<a href="uudised_vene/2007/uudis28_12.htm" target="_top"><font size=2 face="Tahoma" color=red>Подробнее...</font></a><br><br>
		</td></tr>

		<tr><td>
		<font size=2 face="Tahoma" style="color: black"><b>27 ДЕКАБРЯ 2007</font></b><br>
		<font size=2 face="Tahoma">
		<img src="Images1/1.gif">&nbsp; 
		В разделе «Периодика» размещен новый выпуск газеты «Вестник НЭС»<br>
		<a href="http://intranet/default.php?id=10&name=nejteat" target="_top"><font size=2 face="Tahoma" color=red>Подробнее...</font></a><br><br>
		</td></tr>

		<tr><td>
		<font size=2 face="Tahoma" style="color: black"><b>21 ДЕКАБРЯ 2007</font></b><br>
		<font size=2 face="Tahoma">
		<img src="Images1/1.gif">&nbsp; 
		22 декабря – День энергетика<br>
		<a href="uudised_vene/2007/uudis21_12.htm" target="_top"><font size=2 face="Tahoma" color=red>Подробнее...</font></a><br><br>
		<font size=2 face="Tahoma">
		<img src="Images1/1.gif">&nbsp; 
		Покупка квот на выброс парниковых газов сделает центральное отопление дороже<br>
		<a href="uudised_vene/2007/uudis21a_12.htm" target="_top"><font size=2 face="Tahoma" color=red>Подробнее...</font></a><br><br>
		</td></tr>

		<tr><td>
		<font size=2 face="Tahoma" style="color: black"><b>20 ДЕКАБРЯ 2007</font></b><br>
		<font size=2 face="Tahoma">
		<img src="Images1/1.gif">&nbsp; 
		Правительство Эстонии предоставило Александру Кайдалову и Владимиру Шишкову гражданство за особые заслуги<br>
		<a href="uudised_vene/2007/uudis20b_12.htm" target="_top"><font size=2 face="Tahoma" color=red>Подробнее...</font></a><br><br>
		<font size=2 face="Tahoma">
		<img src="Images1/1.gif">&nbsp; 
		Внесение изменений в приказ о переносе рабочих дней в новогодний период<br>
		<a href="uudised_vene/2007/uudis20_12.htm" target="_top"><font size=2 face="Tahoma" color=red>Подробнее...</font></a><br><br>
		<font size=2 face="Tahoma">
		<img src="Images1/1.gif">&nbsp; 
		Новогодние подарки для работников Нарвских электростанций<br>
		<a href="uudised_vene/2007/uudis20a_12.htm" target="_top"><font size=2 face="Tahoma" color=red>Подробнее...</font></a><br><br>
		</td></tr>

		<tr><td>
		<font size=2 face="Tahoma" style="color: black"><b>19 ДЕКАБРЯ 2007</font></b><br>
		<font size=2 face="Tahoma">
		<img src="Images1/1.gif">&nbsp; 
		Объявление о внутреннем конкурсе<br>
		<a href="http://intranet/default.php?id=2&name=kuulutus" target="_top"><font size=2 face="Tahoma" color=red>Подробнее...</font></a><br><br>
		</td></tr>

		<tr><td>
		<font size=2 face="Tahoma" style="color: black"><b>18 ДЕКАБРЯ 2007</font></b><br>
		<font size=2 face="Tahoma">
		<img src="Images1/1.gif">&nbsp; 
		1 ДЕКАБРЯ к счету прибавится акцизный налог за электроэнергию<br>
		<a href="uudised_vene/2007/uudis18_12.htm" target="_top"><font size=2 face="Tahoma" color=red>Подробнее...</font></a><br><br>
		</td></tr>

		<tr><td>
		<font size=2 face="Tahoma" style="color: black"><b>17 ДЕКАБРЯ 2007</font></b><br>
		<font size=2 face="Tahoma">
		<img src="Images1/1.gif">&nbsp; 
		Правительство Эстонии обсуждает предложение предоставить гражданство за особые заслуги<br>
		<a href="uudised_vene/2007/uudis17_12a.htm" target="_top"><font size=2 face="Tahoma" color=red>Подробнее...</font></a><br><br>
		<font size=2 face="Tahoma">
		<img src="Images1/1.gif">&nbsp; 
		В разделе "Производство" размещены акты по подготовке к зиме 2007/2008 года<br>
		<a href="default.php?id=3" target="_top"><font size=2 face="Tahoma" color=red>Подробнее...</font></a><br><br>
		<font size=2 face="Tahoma">
		<img src="Images1/1.gif">&nbsp; 
		Дни энергии: Что принесет с собой будущее и свободный рынок<br>
		<a href="uudised_vene/2007/uudis17_12.htm" target="_top"><font size=2 face="Tahoma" color=red>Подробнее...</font></a><br><br>
		<font size=2 face="Tahoma">
		<img src="Images1/1.gif">&nbsp; 
		Графики работы вахтенного персонала на 2008 г.<br>
		<a href="http://intranet/default.php?id=2" target="_top"><font size=2 face="Tahoma" color=red>Подробнее...</font></a><br><br>
		</td></tr>

		<tr><td>
		<font size=2 face="Tahoma" style="color: black"><b>13 ДЕКАБРЯ 2007</font></b><br>
		<font size=2 face="Tahoma">
		<img src="Images1/1.gif">&nbsp; 
		10 ДЕКАБРЯ 2008 года состоится открытое обсуждение отчета о воздействии на окружающую среду энергетического комплекса, строительство которого планируется на территории Эстонской электростанции.<br>
		<a href="uudised_vene/2007/uudis13_12b.htm" target="_top"><font size=2 face="Tahoma" color=red>Подробнее...</font></a><br><br>	
		<font size=2 face="Tahoma">
		<img src="Images1/1.gif">&nbsp; 
		Дни энергии<br>
		<a href="uudised_vene/2007/uudis13_12a.htm" target="_top"><font size=2 face="Tahoma" color=red>Подробнее...</font></a><br><br>
		<font size=2 face="Tahoma">
		<img src="Images1/1.gif">&nbsp; 
		Сообщение для прессы<br>
		<a href="uudised_vene/2007/uudis13_12.htm" target="_top"><font size=2 face="Tahoma" color=red>Подробнее...</font></a><br><br>
		<font size=2 face="Tahoma">
		<img src="Images1/1.gif">&nbsp; 
		Перенос выходных дней<br>
		<a href="uudised_vene/2007/uudis19_11.htm" target="_top"><font size=2 face="Tahoma" color=red>Подробнее...</font></a><br><br>
		</td></tr>


		<tr><td>
		<font size=2 face="Tahoma" style="color: black"><b>04 ДЕКАБРЯ 2007</font></b><br>
		<font size=2 face="Tahoma">
		<img src="Images1/1.gif">&nbsp; 
		Нарвские предприятия вербуют студентов Вирумааского колледжа<br>
		<a href="uudised_vene\2007\uudis04_12.htm" target="_top"><font size=2 face="Tahoma" color=red>Подробнее...</font></a><br><br>
		</td></tr>

		<tr><td>
		<font size=2 face="Tahoma" style="color: black"><b>03 ДЕКАБРЯ 2007</font></b><br>
		<font size=2 face="Tahoma">
		<img src="Images1/1.gif">&nbsp; 
		Государственная стратегия развития активного отдыха в действии!<br>
		<a href="Dokumentid/vaba_aeg_sport/actpuh.pdf" target="_top"><font size=2 face="Tahoma" color=red>Подробнее...</font></a><br><br>
		<font size=2 face="Tahoma">
		<img src="Images1/1.gif">&nbsp; 
		Новый выпуск внутренней газеты «Вестник НЭС»<br>
		<a href="uudised_vene/2007/uudis03_12a.htm" target="_top"><font size=2 face="Tahoma" color=red>Подробнее...</font></a><br><br>
		<font size=2 face="Tahoma">
		<img src="Images1/1.gif">&nbsp; 
		Вилка для сланцевых энергетиков<br>
		<a href="uudised_vene/2007/uudis03_12.htm" target="_top"><font size=2 face="Tahoma" color=red>Подробнее...</font></a><br><br>
		</td></tr>
		</table>

		<p align=right>
		<font face="Tahoma" size=2 color=black>
		<a href="javascript:history.back(1)" target="_top" alt="Назад"><font face="Tahoma" size=2 color=#3f8cff><u><<<</u></a></font>
		</p>

		<br>
		<center>
		<a href="" TARGET="_top"><img src="image/intra_m.gif" alt="На главную страницу" border="0"></a><br><br><br>